# Generated by Django 4.1.5 on 2023-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=255, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenure',
            field=models.IntegerField(default=0, verbose_name='tenure'),
        ),
    ]
