# Generated by Django 4.1.5 on 2023-01-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_state_user_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pto',
            field=models.IntegerField(default=10, verbose_name='pto'),
        ),
    ]
