# Generated by Django 4.1.5 on 2023-01-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_pto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pto',
            field=models.IntegerField(default=80, verbose_name='pto'),
        ),
    ]
