# Generated by Django 4.1.5 on 2023-01-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_for_pto', '0002_remove_request_decision_remove_request_is_pending_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_request',
            old_name='request',
            new_name='request_for_pto',
        ),
    ]
