# Generated by Django 4.1.5 on 2023-01-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_for_pto', '0003_rename_request_employee_request_request_for_pto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='users',
        ),
    ]
