# Generated by Django 4.1.5 on 2023-01-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests_for_pto', '0004_remove_request_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='users',
            field=models.ManyToManyField(blank=True, through='requests_for_pto.Employee_Request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee_request',
            name='request_for_pto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_for_pto', to='requests_for_pto.request', verbose_name='request_for_pto'),
        ),
        migrations.AlterField(
            model_name='employee_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='manager_employee',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
