# Generated by Django 4.1.5 on 2023-01-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_for_pto', '0005_request_users_alter_employee_request_request_for_pto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='users',
        ),
        migrations.AddField(
            model_name='request',
            name='decision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
