# Generated by Django 4.1.5 on 2023-01-20 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests_for_pto', '0006_remove_request_users_request_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_request',
            name='request_for_pto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pto_request', to='requests_for_pto.request'),
        ),
        migrations.AlterField(
            model_name='employee_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager_employee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager_employee',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_emplyee', to=settings.AUTH_USER_MODEL),
        ),
    ]
