# Generated by Django 4.1.5 on 2023-01-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_for_pto', '0007_alter_employee_request_request_for_pto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.CharField(default='emily', max_length=255),
            preserve_default=False,
        ),
    ]
