# Generated by Django 4.1.5 on 2023-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_for_pto', '0010_frequency_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=80)),
            ],
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.RenameField(
            model_name='frequency',
            old_name='frequency1',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='frequency2',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='frequency3',
        ),
    ]
