# Generated by Django 4.1.5 on 2023-02-07 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_for_pto', '0011_hour_delete_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='submission_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
